version: "3"

services:
  shlink:
    image: shlinkio/shlink:stable
    restart: unless-stopped
    environment:
      - TZ="Europe/Paris"
      - DEFAULT_DOMAIN=domain.com
      - IS_HTTPS_ENABLED=true
      - DB_DRIVER=postgres
      - DB_USER=shlink
      - DB_NAME=shlink
      - DB_PASSWORD=password
      - DB_HOST=database
    depends_on:
      - database
    ports:
      - 8081:8080

  database:
    image: postgres:alpine
    restart: unless-stopped
    volumes:
      - /DATA/AppData/shlink/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=shlink
      - POSTGRES_DB=shlink

  shlink-web-client:
    image: shlinkio/shlink-web-client
    restart: unless-stopped
    volumes:
      - /DATA/AppData/shlink/servers.json:/usr/share/nginx/html/servers.json
    ports:
      - 8082:8080