name: shlink

services:

# Shlink web-client
  shlink-web-client:
    image: shlinkio/shlink-web-client:stable
    container_name: web-client
    hostname: web-client
    restart: unless-stopped

    depends_on:
      shlink:
        condition: service_started
        required: true
    
    ports:
      - target: 8080
        published: "8082"
        protocol: tcp
    
    volumes:
      - type: bind
        source: /DATA/AppData/shlink
        target: /usr/share/nginx/html
        bind:
          create_host_path: true
    x-casaos:
      ports:
        - container: "8080"
          description:
            en_us: Web UI port
      volumes:
        - container: /usr/share/nginx/html
          description:
            en_us: Web client server data

    command: touch /usr/share/nginx/html/servers.json

    network_mode: shlink_default
  
# Shlink backend
  shlink:
    image: shlinkio/shlink:stable
    container_name: shlink
    hostname: shlink
    restart: unless-stopped

    depends_on:
      database:
        condition: service_started
        required: true
    
    environment:
      - DB_DRIVER=postgres
      - DB_HOST=database
      - DB_NAME=shlink
      - DB_PASSWORD=password
      - DB_USER=shlink
      - DEFAULT_DOMAIN=domain.com
      - IS_HTTPS_ENABLED=true
      - TZ=Europe/Paris
    
    ports:
      - target: 8080
        published: "8081"
        protocol: tcp
    
    x-casaos:
      envs:
        - container: TZ
          description:
            en_us: The Time zone in use
        - container: DEFAULT_DOMAIN
          description:
            en_us: The Domain to be used for shortening
        - container: IS_HTTPS_ENABLED
          description:
            en_us: Enable HTTPS
      ports:
        - container: "8080"
          description:
            en_us: API port

    network_mode: shlink_default

# postgres database
  database:
    image: postgres:latest
    hostname: database
    container_name: database
    restart: unless-stopped

    environment:
      - POSTGRES_DB=shlink
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=shlink
    
    volumes:
      - type: bind
        source: /DATA/AppData/shlink/postgres
        target: /var/lib/postgresql/data
        bind:
          create_host_path: true

    x-casaos:
      volumes:
        - container: /var/lib/postgresql/data
          description:
            en_us: Postgres data directory

    network_mode: shlink_default

networks:
  shlink_default:
    driver: bridge
    name: shlink_default

x-casaos:
  architectures:
    - amd64
    - arm64
  author: Kleeat
  category: self
  description:
    en_us: Shlink is a self-hosted url shortener.
  developer: Shlinkio
  hostname: ""
  icon: https://cdn.jsdelivr.net/gh/Kleeat/CasaOS-LambdaStore@main/Apps/Shlink/icon.png
  index: /
  main: shlink
  port_map: "8082"
  scheme: http
  store_app_id: shlink
  tagline:
    en_us: Short urls with a click
  # tips:
  #   before_install:
  #     en_us: |
  #       Before installing the servers.json must be manually created.
  title:
    custom: ""
    en_us: Shlink